# Generated by Django 5.2 on 2026-05-31 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='empresa',
            new_name='empresas_em_cnpj_fe5b68_idx',
            old_name='empresas_em_cnpj_idx',
        ),
        migrations.RenameIndex(
            model_name='empresa',
            new_name='empresas_em_is_acti_945722_idx',
            old_name='empresas_em_is_acti_idx',
        ),
    ]
