# Generated by Django 5.2 on 2026-05-31 18:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_financeiras', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Categoria Financeira',
                'verbose_name_plural': 'Categorias Financeiras',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('CAIXA', 'Caixa'), ('BANCO', 'Banco'), ('CARTEIRA', 'Carteira'), ('OUTRO', 'Outro')], max_length=20)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaixaDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_entradas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_saidas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saldo_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('aberto_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_diarios', to='empresas.empresa')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL)),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_diarios', to='financeiro.contafinanceira')),
            ],
            options={
                'verbose_name': 'Caixa Diário',
                'verbose_name_plural': 'Caixas Diários',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_restante', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_canceladas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financeiro.categoriafinanceira')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='empresas.empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_criadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='estoque.fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True)),
                ('origem_tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('FIADO', 'Fiado'), ('CONTA_PAGAR', 'Conta a pagar'), ('ESTORNO', 'Estorno'), ('AJUSTE', 'Ajuste')], default='MANUAL', max_length=30)),
                ('origem_id', models.UUIDField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO', 'Cartão'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=140)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('caixa_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.caixadiario')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros_cancelados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoriafinanceira')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='empresas.empresa')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contafinanceira')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros_criados', to=settings.AUTH_USER_MODEL)),
                ('estorno_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='financeiro.lancamentofinanceiro')),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='categoriafinanceira',
            index=models.Index(fields=['company', 'nome'], name='financeiro__company_dc6e54_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriafinanceira',
            index=models.Index(fields=['company', 'tipo'], name='financeiro__company_a1b767_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriafinanceira',
            index=models.Index(fields=['company', 'ativa'], name='financeiro__company_55a831_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'nome', 'tipo'), name='financeiro_unique_categoria_nome_tipo_company_active'),
        ),
        migrations.AddIndex(
            model_name='contafinanceira',
            index=models.Index(fields=['company', 'nome'], name='financeiro__company_8304f7_idx'),
        ),
        migrations.AddIndex(
            model_name='contafinanceira',
            index=models.Index(fields=['company', 'tipo'], name='financeiro__company_c328ee_idx'),
        ),
        migrations.AddIndex(
            model_name='contafinanceira',
            index=models.Index(fields=['company', 'ativo'], name='financeiro__company_1b5c0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'nome'), name='financeiro_unique_conta_nome_company_active'),
        ),
        migrations.AddConstraint(
            model_name='contafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_atual__gte', 0)), name='financeiro_conta_saldo_atual_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='caixadiario',
            index=models.Index(fields=['company', 'data'], name='financeiro__company_e14410_idx'),
        ),
        migrations.AddIndex(
            model_name='caixadiario',
            index=models.Index(fields=['company', 'status'], name='financeiro__company_91912c_idx'),
        ),
        migrations.AddIndex(
            model_name='caixadiario',
            index=models.Index(fields=['company', 'conta_financeira', 'data'], name='financeiro__company_de4044_idx'),
        ),
        migrations.AddConstraint(
            model_name='caixadiario',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ABERTO')), fields=('company', 'data'), name='financeiro_unique_caixa_aberto_company_data'),
        ),
        migrations.AddConstraint(
            model_name='caixadiario',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_inicial__gte', 0)), name='financeiro_caixa_saldo_inicial_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='caixadiario',
            constraint=models.CheckConstraint(condition=models.Q(('total_entradas__gte', 0)), name='financeiro_caixa_total_entradas_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='caixadiario',
            constraint=models.CheckConstraint(condition=models.Q(('total_saidas__gte', 0)), name='financeiro_caixa_total_saidas_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='caixadiario',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_final__gte', 0)), name='financeiro_caixa_saldo_final_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['company', 'status', 'data_vencimento'], name='financeiro__company_412283_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['company', 'fornecedor', 'data_vencimento'], name='financeiro__company_e52241_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['company', 'categoria', 'data_vencimento'], name='financeiro__company_e312c2_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['company', 'created_by', 'created_at'], name='financeiro__company_de3b31_idx'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='financeiro_conta_pagar_total_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago__gte', 0)), name='financeiro_conta_pagar_pago_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='contapagar',
            constraint=models.CheckConstraint(condition=models.Q(('valor_restante__gte', 0)), name='financeiro_conta_pagar_restante_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['company', 'tipo'], name='financeiro__company_e44861_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['company', 'status'], name='financeiro__company_09db9f_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['company', 'data_lancamento'], name='financeiro__company_43e377_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['company', 'origem_tipo', 'origem_id'], name='financeiro__company_e29d91_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['company', 'idempotency_key'], name='financeiro__company_e4446f_idx'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='financeiro_unique_lancamento_key_company_active'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('estorno_de__isnull', False)), fields=('company', 'estorno_de'), name='financeiro_unique_estorno_lancamento_company_active'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='financeiro_lancamento_valor_gt_zero'),
        ),
    ]
