# Generated by Codex on 2026-06-03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
        ("empresas", "0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoFinanceiraOperacional",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuracao_financeira_operacional",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "conta_cartao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuracoes_cartao",
                        to="financeiro.contafinanceira",
                    ),
                ),
                (
                    "conta_dinheiro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuracoes_dinheiro",
                        to="financeiro.contafinanceira",
                    ),
                ),
                (
                    "conta_pix",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuracoes_pix",
                        to="financeiro.contafinanceira",
                    ),
                ),
                (
                    "conta_transferencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuracoes_transferencia",
                        to="financeiro.contafinanceira",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuracoes_financeiras_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração Financeira Operacional",
                "verbose_name_plural": "Configurações Financeiras Operacionais",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="configuracaofinanceiraoperacional",
            index=models.Index(fields=["company"], name="financeiro__company_c92b85_idx"),
        ),
    ]
