# Generated by Django 5.2 on 2026-05-31 12:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_rename_clientes_cl_company_bloq_idx_clientes_cl_company_b7e5dc_idx_and_more'),
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFiado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_restante', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_fiado_canceladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_fiado', to='clientes.cliente')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_fiado_fechadas', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_fiado', to='empresas.empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_fiado_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Fiado',
                'verbose_name_plural': 'Contas Fiado',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemFiado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_fiado_cancelados', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_fiado', to='empresas.empresa')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='fiado.contafiado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_fiado_criados', to=settings.AUTH_USER_MODEL)),
                ('movimentacao_cancelamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_fiado_cancelamento', to='estoque.movimentacaoestoque')),
                ('movimentacao_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_fiado_origem', to='estoque.movimentacaoestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_fiado', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Item Fiado',
                'verbose_name_plural': 'Itens Fiado',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagamentoFiado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO', 'Cartão'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_fiado_cancelados', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_fiado', to='empresas.empresa')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='fiado.contafiado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_fiado_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento Fiado',
                'verbose_name_plural': 'Pagamentos Fiado',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoFiado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('evento', models.CharField(choices=[('CONTA_CRIADA', 'Conta criada'), ('ITEM_ADICIONADO', 'Item adicionado'), ('ITEM_CANCELADO', 'Item cancelado'), ('PAGAMENTO_REGISTRADO', 'Pagamento registrado'), ('PAGAMENTO_CANCELADO', 'Pagamento cancelado'), ('CONTA_FECHADA', 'Conta fechada'), ('CONTA_CANCELADA', 'Conta cancelada'), ('VENCIMENTO_ALTERADO', 'Vencimento alterado'), ('OBSERVACAO_ALTERADA', 'Observação alterada')], max_length=40)),
                ('descricao', models.TextField()),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_fiado', to='empresas.empresa')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='fiado.contafiado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_fiado', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='fiado.itemfiado')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='fiado.pagamentofiado')),
            ],
            options={
                'verbose_name': 'Histórico Fiado',
                'verbose_name_plural': 'Históricos Fiado',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='contafiado',
            index=models.Index(fields=['company', 'cliente', 'status'], name='fiado_conta_company_9fe990_idx'),
        ),
        migrations.AddIndex(
            model_name='contafiado',
            index=models.Index(fields=['company', 'status', 'data_vencimento'], name='fiado_conta_company_d9205c_idx'),
        ),
        migrations.AddIndex(
            model_name='contafiado',
            index=models.Index(fields=['company', 'cliente', 'created_at'], name='fiado_conta_company_e17581_idx'),
        ),
        migrations.AddIndex(
            model_name='contafiado',
            index=models.Index(fields=['company', 'created_by', 'created_at'], name='fiado_conta_company_39ff76_idx'),
        ),
        migrations.AddIndex(
            model_name='contafiado',
            index=models.Index(fields=['company', 'valor_restante'], name='fiado_conta_company_698025_idx'),
        ),
        migrations.AddConstraint(
            model_name='contafiado',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ABERTA'), ('deleted_at__isnull', True)), fields=('company', 'cliente'), name='fiado_unique_conta_aberta_cliente_company'),
        ),
        migrations.AddConstraint(
            model_name='contafiado',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='fiado_conta_valor_total_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='contafiado',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago__gte', 0)), name='fiado_conta_valor_pago_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='contafiado',
            constraint=models.CheckConstraint(condition=models.Q(('valor_restante__gte', 0)), name='fiado_conta_valor_restante_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='itemfiado',
            index=models.Index(fields=['company', 'conta', 'status'], name='fiado_itemf_company_cd98c7_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfiado',
            index=models.Index(fields=['company', 'produto', 'created_at'], name='fiado_itemf_company_3e23f0_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfiado',
            index=models.Index(fields=['company', 'created_by', 'created_at'], name='fiado_itemf_company_03c17a_idx'),
        ),
        migrations.AddIndex(
            model_name='itemfiado',
            index=models.Index(fields=['company', 'idempotency_key'], name='fiado_itemf_company_9a3765_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemfiado',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='fiado_unique_item_key_company_active'),
        ),
        migrations.AddConstraint(
            model_name='itemfiado',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('movimentacao_estoque__isnull', False)), fields=('company', 'movimentacao_estoque'), name='fiado_unique_item_mov_saida_company_active'),
        ),
        migrations.AddConstraint(
            model_name='itemfiado',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('movimentacao_cancelamento__isnull', False)), fields=('company', 'movimentacao_cancelamento'), name='fiado_unique_item_mov_cancel_company_active'),
        ),
        migrations.AddConstraint(
            model_name='itemfiado',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='fiado_item_quantidade_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='itemfiado',
            constraint=models.CheckConstraint(condition=models.Q(('preco_unitario__gte', 0)), name='fiado_item_preco_unitario_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='itemfiado',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='fiado_item_subtotal_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='pagamentofiado',
            index=models.Index(fields=['company', 'conta', 'status'], name='fiado_pagam_company_275e42_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentofiado',
            index=models.Index(fields=['company', 'forma_pagamento', 'data_pagamento'], name='fiado_pagam_company_c4f9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentofiado',
            index=models.Index(fields=['company', 'created_by', 'created_at'], name='fiado_pagam_company_f529e3_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentofiado',
            index=models.Index(fields=['company', 'idempotency_key'], name='fiado_pagam_company_632d21_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagamentofiado',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='fiado_unique_pagamento_key_company_active'),
        ),
        migrations.AddConstraint(
            model_name='pagamentofiado',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='fiado_pagamento_valor_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='historicofiado',
            index=models.Index(fields=['company', 'conta', 'created_at'], name='fiado_histo_company_fd8f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='historicofiado',
            index=models.Index(fields=['company', 'evento', 'created_at'], name='fiado_histo_company_b96828_idx'),
        ),
        migrations.AddIndex(
            model_name='historicofiado',
            index=models.Index(fields=['company', 'created_by', 'created_at'], name='fiado_histo_company_6615e9_idx'),
        ),
    ]
