# Generated by Django 5.2 on 2026-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiado', '0002_itemfiado_forma_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicofiado',
            name='evento',
            field=models.CharField(choices=[('CONTA_CRIADA', 'Conta criada'), ('ITEM_ADICIONADO', 'Item adicionado'), ('ITEM_CANCELADO', 'Item cancelado'), ('PAGAMENTO_REGISTRADO', 'Pagamento registrado'), ('PAGAMENTO_CANCELADO', 'Pagamento cancelado'), ('CONTA_FECHADA', 'Conta fechada'), ('CONTA_CANCELADA', 'Conta cancelada'), ('VENCIMENTO_ALTERADO', 'Vencimento alterado'), ('OBSERVACAO_ALTERADA', 'Observação alterada'), ('COBRANCA_ENVIADA', 'Cobrança enviada'), ('COBRANCA_ENTREGUE', 'Cobrança entregue'), ('COBRANCA_LIDA', 'Cobrança lida'), ('COBRANCA_FALHOU', 'Cobrança falhou')], max_length=40),
        ),
    ]
