# Generated by Django 5.2 on 2026-05-31 19:05

import apps.boletos.services.storage
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
        ('estoque', '0001_initial'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletoOCR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('arquivo', models.FileField(upload_to=apps.boletos.services.storage.boleto_upload_path)),
                ('arquivo_nome_original', models.CharField(max_length=255)),
                ('tipo_arquivo', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('JPEG', 'JPEG'), ('PNG', 'PNG'), ('WEBP', 'WEBP')], max_length=10)),
                ('content_type', models.CharField(max_length=120)),
                ('tamanho_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=apps.boletos.services.storage.preview_upload_path)),
                ('preview_pages', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('PROCESSANDO', 'Processando'), ('AGUARDANDO_REVISAO', 'Aguardando revisão'), ('CONFIRMADO', 'Confirmado'), ('REJEITADO', 'Rejeitado'), ('ERRO', 'Erro')], default='ENVIADO', max_length=30)),
                ('fornecedor_nome', models.CharField(blank=True, max_length=300)),
                ('documento_beneficiario', models.CharField(blank=True, max_length=20)),
                ('documento_pagador', models.CharField(blank=True, max_length=20)),
                ('banco_codigo', models.CharField(blank=True, max_length=10)),
                ('banco_nome', models.CharField(blank=True, max_length=120)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('linha_digitavel', models.CharField(blank=True, max_length=80)),
                ('codigo_barras', models.CharField(blank=True, max_length=60)),
                ('texto_ocr', models.TextField(blank=True)),
                ('payload_ocr', models.JSONField(blank=True, default=dict)),
                ('raw_provider_response', models.JSONField(blank=True, default=dict)),
                ('campos_extraidos', models.JSONField(blank=True, default=dict)),
                ('campos_confianca', models.JSONField(blank=True, default=dict)),
                ('confianca_ocr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('ocr_started_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_finished_at', models.DateTimeField(blank=True, null=True)),
                ('confirmado_at', models.DateTimeField(blank=True, null=True)),
                ('rejeitado_at', models.DateTimeField(blank=True, null=True)),
                ('erro_codigo', models.CharField(blank=True, max_length=80)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('tentativas_ocr', models.PositiveSmallIntegerField(default=0)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=140)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_ocr', to='empresas.empresa')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('conta_pagar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boleto_ocr', to='financeiro.contapagar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_enviados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos_ocr', to='estoque.fornecedor')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_processados', to=settings.AUTH_USER_MODEL)),
                ('rejeitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_rejeitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleto OCR',
                'verbose_name_plural': 'Boletos OCR',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoBoleto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('evento', models.CharField(choices=[('UPLOAD_REALIZADO', 'Upload realizado'), ('OCR_INICIADO', 'OCR iniciado'), ('OCR_CONCLUIDO', 'OCR concluído'), ('OCR_FALHOU', 'OCR falhou'), ('OCR_REPROCESSADO', 'OCR reprocessado'), ('CONFIRMADO', 'Confirmado'), ('REJEITADO', 'Rejeitado'), ('CONTA_PAGAR_CRIADA', 'Conta a pagar criada')], max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='boletos.boletoocr')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_boletos', to='empresas.empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_boletos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Boleto',
                'verbose_name_plural': 'Históricos de Boletos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OCRProcessamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('GOOGLE_VISION', 'Google Vision'), ('FAKE', 'Fake')], max_length=30)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('TIMEOUT', 'Timeout')], default='PROCESSANDO', max_length=20)),
                ('tentativa', models.PositiveSmallIntegerField()),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('texto_extraido', models.TextField(blank=True)),
                ('payload_response', models.JSONField(blank=True, default=dict)),
                ('raw_provider_response', models.JSONField(blank=True, default=dict)),
                ('erro_codigo', models.CharField(blank=True, max_length=80)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('confianca_ocr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processamentos', to='boletos.boletoocr')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocr_processamentos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Processamento OCR',
                'verbose_name_plural': 'Processamentos OCR',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='boletoocr',
            index=models.Index(fields=['company', 'status', 'created_at'], name='boletos_bol_company_2f70a1_idx'),
        ),
        migrations.AddIndex(
            model_name='boletoocr',
            index=models.Index(fields=['company', 'vencimento'], name='boletos_bol_company_bda9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='boletoocr',
            index=models.Index(fields=['company', 'fornecedor', 'vencimento'], name='boletos_bol_company_626e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='boletoocr',
            index=models.Index(fields=['company', 'created_by', 'created_at'], name='boletos_bol_company_cea8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='boletoocr',
            index=models.Index(fields=['company', 'conta_pagar'], name='boletos_bol_company_40daab_idx'),
        ),
        migrations.AddConstraint(
            model_name='boletoocr',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='boletos_unique_idempotency_company_active'),
        ),
        migrations.AddConstraint(
            model_name='boletoocr',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('sha256', ''), _negated=True)), fields=('company', 'sha256'), name='boletos_unique_sha256_company_active'),
        ),
        migrations.AddConstraint(
            model_name='boletoocr',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('linha_digitavel', ''), _negated=True)), fields=('company', 'linha_digitavel'), name='boletos_unique_linha_company_active'),
        ),
        migrations.AddConstraint(
            model_name='boletoocr',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('codigo_barras', ''), _negated=True)), fields=('company', 'codigo_barras'), name='boletos_unique_codigo_company_active'),
        ),
        migrations.AddConstraint(
            model_name='boletoocr',
            constraint=models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gt', 0), _connector='OR'), name='boletos_valor_gt_zero_or_null'),
        ),
        migrations.AddConstraint(
            model_name='boletoocr',
            constraint=models.CheckConstraint(condition=models.Q(('confianca_ocr__gte', 0), ('confianca_ocr__lte', 100)), name='boletos_confianca_between_0_100'),
        ),
        migrations.AddIndex(
            model_name='historicoboleto',
            index=models.Index(fields=['company', 'boleto', 'created_at'], name='boletos_his_company_11a75d_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoboleto',
            index=models.Index(fields=['company', 'evento', 'created_at'], name='boletos_his_company_79dd23_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoboleto',
            index=models.Index(fields=['created_by', 'created_at'], name='boletos_his_created_881071_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrprocessamento',
            index=models.Index(fields=['company', 'boleto', 'tentativa'], name='boletos_ocr_company_a2b9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrprocessamento',
            index=models.Index(fields=['company', 'status', 'created_at'], name='boletos_ocr_company_b4a4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrprocessamento',
            index=models.Index(fields=['task_id'], name='boletos_ocr_task_id_cb0435_idx'),
        ),
    ]
