# Generated by Django 5.2 on 2026-05-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_auditlog_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
