# Generated by Django 5.2 on 2026-05-31 23:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail')], max_length=20)),
                ('nome', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('META_CLOUD', 'Meta Cloud API')], max_length=40)),
                ('configuracao', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canais_notificacao', to='empresas.empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_notificacao_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canal de Notificação',
                'verbose_name_plural': 'Canais de Notificação',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoWebhookWhatsApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='META_CLOUD', max_length=40)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_webhook_whatsapp', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Evento Webhook WhatsApp',
                'verbose_name_plural': 'Eventos Webhook WhatsApp',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateNotificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('COBRANCA_FIADO', 'Cobrança de Fiado'), ('LEMBRETE_VENCIMENTO', 'Lembrete de Vencimento'), ('CONFIRMACAO_PAGAMENTO', 'Confirmação de Pagamento'), ('RESUMO_CONTA', 'Resumo da Conta'), ('AVISO_ATRASO', 'Aviso de Conta Atrasada')], max_length=40)),
                ('provider_template_name', models.CharField(blank=True, max_length=120)),
                ('linguagem', models.CharField(default='pt_BR', max_length=10)),
                ('categoria', models.CharField(choices=[('UTILITY', 'Utilidade'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Autenticação')], default='UTILITY', max_length=20)),
                ('corpo', models.TextField(blank=True)),
                ('variaveis', models.JSONField(blank=True, default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='notificacoes.canalnotificacao')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates_notificacao', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('COBRANCA_FIADO', 'Cobrança de Fiado'), ('LEMBRETE_VENCIMENTO', 'Lembrete de Vencimento'), ('CONFIRMACAO_PAGAMENTO', 'Confirmação de Pagamento'), ('RESUMO_CONTA', 'Resumo da Conta'), ('AVISO_ATRASO', 'Aviso de Conta Atrasada')], max_length=40)),
                ('destinatario_nome', models.CharField(max_length=255)),
                ('destinatario_contato', models.CharField(max_length=50)),
                ('mensagem', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENFILEIRADA', 'Enfileirada'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('FALHOU', 'Falhou'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('erro_codigo', models.CharField(blank=True, max_length=80)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('origem_tipo', models.CharField(blank=True, max_length=80)),
                ('origem_id', models.UUIDField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=180)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='notificacoes.canalnotificacao')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='empresas.empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='notificacoes.templatenotificacao')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='canalnotificacao',
            index=models.Index(fields=['company', 'tipo', 'ativo'], name='notificacoe_company_48be2e_idx'),
        ),
        migrations.AddIndex(
            model_name='canalnotificacao',
            index=models.Index(fields=['company', 'provider'], name='notificacoe_company_5bc8da_idx'),
        ),
        migrations.AddConstraint(
            model_name='canalnotificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('deleted_at__isnull', True)), fields=('company', 'tipo'), name='notif_unique_canal_ativo_tipo_company'),
        ),
        migrations.AddIndex(
            model_name='eventowebhookwhatsapp',
            index=models.Index(fields=['provider_message_id', 'processed'], name='notificacoe_provide_80d741_idx'),
        ),
        migrations.AddIndex(
            model_name='eventowebhookwhatsapp',
            index=models.Index(fields=['received_at'], name='notificacoe_receive_7b0498_idx'),
        ),
        migrations.AddIndex(
            model_name='templatenotificacao',
            index=models.Index(fields=['company', 'tipo', 'ativo'], name='notificacoe_company_553abe_idx'),
        ),
        migrations.AddIndex(
            model_name='templatenotificacao',
            index=models.Index(fields=['company', 'canal', 'ativo'], name='notificacoe_company_245074_idx'),
        ),
        migrations.AddConstraint(
            model_name='templatenotificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('deleted_at__isnull', True)), fields=('company', 'tipo', 'canal'), name='notif_unique_template_ativo_tipo_canal'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['company', 'status', 'created_at'], name='notificacoe_company_c54abc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['company', 'tipo', 'created_at'], name='notificacoe_company_2586dd_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['company', 'origem_tipo', 'origem_id'], name='notificacoe_company_d8658d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['company', 'destinatario_contato'], name='notificacoe_company_2b6af7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['company', 'created_by', 'created_at'], name='notificacoe_company_e25391_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['company', 'sent_at'], name='notificacoe_company_9ef9b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificacao',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='notif_unique_idempotency_key_company'),
        ),
    ]
