# Generated by Django 5.2 on 2026-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('COBRANCA_FIADO', 'Cobrança de Fiado'), ('LEMBRETE_VENCIMENTO', 'Lembrete de Vencimento'), ('COBRANCA_1_DIA', 'Cobrança 1 dia após vencimento'), ('COBRANCA_7_DIAS', 'Cobrança 7 dias após vencimento'), ('COBRANCA_15_DIAS', 'Cobrança 15 dias após vencimento'), ('COBRANCA_30_DIAS', 'Cobrança 30 dias após vencimento'), ('CONFIRMACAO_PAGAMENTO', 'Confirmação de Pagamento'), ('AGRADECIMENTO_PAGAMENTO', 'Agradecimento de Pagamento'), ('RESUMO_CONTA', 'Resumo da Conta'), ('AVISO_ATRASO', 'Aviso de Conta Atrasada')], max_length=40),
        ),
        migrations.AlterField(
            model_name='templatenotificacao',
            name='tipo',
            field=models.CharField(choices=[('COBRANCA_FIADO', 'Cobrança de Fiado'), ('LEMBRETE_VENCIMENTO', 'Lembrete de Vencimento'), ('COBRANCA_1_DIA', 'Cobrança 1 dia após vencimento'), ('COBRANCA_7_DIAS', 'Cobrança 7 dias após vencimento'), ('COBRANCA_15_DIAS', 'Cobrança 15 dias após vencimento'), ('COBRANCA_30_DIAS', 'Cobrança 30 dias após vencimento'), ('CONFIRMACAO_PAGAMENTO', 'Confirmação de Pagamento'), ('AGRADECIMENTO_PAGAMENTO', 'Agradecimento de Pagamento'), ('RESUMO_CONTA', 'Resumo da Conta'), ('AVISO_ATRASO', 'Aviso de Conta Atrasada')], max_length=40),
        ),
    ]
