# Generated by Django 5.2 on 2026-05-31 03:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_produto', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produto',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('razao_social', models.CharField(max_length=300)),
                ('nome_fantasia', models.CharField(blank=True, max_length=300)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacoes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('codigo_barras', models.CharField(blank=True, max_length=80)),
                ('preco_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('custo_medio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.categoriaproduto')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='empresas.empresa')),
                ('fornecedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('DEVOLUCAO', 'Devolução'), ('CANCELAMENTO', 'Cancelamento')], max_length=20)),
                ('quantidade_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('estoque_antes', models.DecimalField(decimal_places=3, max_digits=14)),
                ('estoque_depois', models.DecimalField(decimal_places=3, max_digits=14)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='empresas.empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='estoque.fornecedor')),
                ('movimentacao_cancelada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos', to='estoque.movimentacaoestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=120)),
                ('sigla', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_medida', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.unidademedida'),
        ),
        migrations.AddIndex(
            model_name='categoriaproduto',
            index=models.Index(fields=['company', 'nome'], name='estoque_cat_company_82e8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaproduto',
            index=models.Index(fields=['company', 'is_active'], name='estoque_cat_company_9ebbcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'nome'), name='estoque_unique_categoria_nome_company_active'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['company', 'razao_social'], name='estoque_for_company_e2a670_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['company', 'cnpj'], name='estoque_for_company_473912_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['company', 'is_active'], name='estoque_for_company_9cda31_idx'),
        ),
        migrations.AddConstraint(
            model_name='fornecedor',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'cnpj'), name='estoque_unique_fornecedor_cnpj_company_active'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['company', 'produto', 'created_at'], name='estoque_mov_company_d9df31_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['company', 'tipo', 'created_at'], name='estoque_mov_company_bad5be_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['company', 'status', 'created_at'], name='estoque_mov_company_26d251_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['company', 'fornecedor', 'created_at'], name='estoque_mov_company_0bda1d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['company', 'created_by', 'created_at'], name='estoque_mov_company_786983_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['company', 'idempotency_key'], name='estoque_mov_company_55339d_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='estoque_unique_mov_key_company_active'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_delta', 0), _negated=True), name='estoque_mov_quantidade_delta_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_antes__gte', 0)), name='estoque_mov_estoque_antes_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_depois__gte', 0)), name='estoque_mov_estoque_depois_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='unidademedida',
            index=models.Index(fields=['company', 'sigla'], name='estoque_uni_company_b30f44_idx'),
        ),
        migrations.AddIndex(
            model_name='unidademedida',
            index=models.Index(fields=['company', 'nome'], name='estoque_uni_company_c42507_idx'),
        ),
        migrations.AddConstraint(
            model_name='unidademedida',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'sigla'), name='estoque_unique_unidade_sigla_company_active'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['company', 'nome'], name='estoque_pro_company_283faf_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['company', 'categoria'], name='estoque_pro_company_d38924_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['company', 'fornecedor_principal'], name='estoque_pro_company_835b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['company', 'unidade'], name='estoque_pro_company_781a11_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['company', 'is_active'], name='estoque_pro_company_71650b_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['company', 'estoque_atual'], name='estoque_pro_company_a710d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('sku', ''), _negated=True)), fields=('company', 'sku'), name='estoque_unique_produto_sku_company_active'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('codigo_barras', ''), _negated=True)), fields=('company', 'codigo_barras'), name='estoque_unique_produto_barcode_company_active'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_atual__gte', 0)), name='estoque_produto_estoque_atual_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_minimo__gte', 0)), name='estoque_produto_estoque_minimo_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_compra__gte', 0)), name='estoque_produto_preco_compra_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_venda__gte', 0)), name='estoque_produto_preco_venda_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('custo_medio__gte', 0)), name='estoque_produto_custo_medio_gte_zero'),
        ),
    ]
