# Generated by Django 5.2 on 2026-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
        ('estoque', '0003_data_default_formas_venda'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='formavendaproduto',
            name='estoque_unique_forma_venda_codigo',
        ),
        migrations.RemoveConstraint(
            model_name='formavendaproduto',
            name='estoque_unique_forma_venda_padrao_por_produto',
        ),
        migrations.RenameIndex(
            model_name='formavendaproduto',
            new_name='estoque_for_company_ba8624_idx',
            old_name='estoque_formavendaproduto_company_produto_ativo',
        ),
        migrations.RenameIndex(
            model_name='formavendaproduto',
            new_name='estoque_for_company_5a0b59_idx',
            old_name='estoque_formavendaproduto_company_produto_padrao',
        ),
        migrations.AddConstraint(
            model_name='formavendaproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('codigo', ''), _negated=True)), fields=('company', 'produto', 'codigo'), name='estoque_unique_forma_venda_codigo'),
        ),
        migrations.AddConstraint(
            model_name='formavendaproduto',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('padrao', True), ('ativo', True)), fields=('company', 'produto'), name='estoque_unique_forma_venda_padrao_por_produto'),
        ),
    ]
