# Generated by Django 5.2 on 2026-06-02 14:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_formavendaproduto_estoque_unique_forma_venda_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_cofins',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_icms',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_ipi',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_pis',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='cfop_padrao',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_beneficio_fiscal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_csosn',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='produto',
            name='ean_tributavel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem_mercadoria',
            field=models.CharField(choices=[('0', 'Nacional'), ('1', 'Estrangeira - importação direta'), ('2', 'Estrangeira - adquirida no mercado interno'), ('3', 'Nacional com importação > 40%'), ('4', 'Nacional PPB'), ('5', 'Nacional com importação <= 40%'), ('6', 'Estrangeira direta sem similar'), ('7', 'Estrangeira mercado interno sem similar'), ('8', 'Nacional com importação > 70%')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_tributavel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
