# Generated by Django 5.2 on 2026-06-03 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCobranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('enviar_1_dia_antes', models.BooleanField(default=False)),
                ('enviar_no_vencimento', models.BooleanField(default=True)),
                ('enviar_7_dias_apos', models.BooleanField(default=True)),
                ('enviar_15_dias_apos', models.BooleanField(default=True)),
                ('enviar_30_dias_apos', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_cobranca', to='empresas.empresa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_cobranca_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Cobrança',
                'verbose_name_plural': 'Configurações de Cobrança',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['company', 'ativo'], name='cobrancas_c_company_e08731_idx')],
            },
        ),
    ]
