# Generated by Django 5.2 on 2026-06-02 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscalEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cnpj', models.CharField(blank=True, max_length=14)),
                ('razao_social', models.CharField(blank=True, max_length=300)),
                ('nome_fantasia', models.CharField(blank=True, max_length=300)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30)),
                ('regime_tributario', models.CharField(blank=True, choices=[('SIMPLES_NACIONAL', 'Simples Nacional'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('LUCRO_REAL', 'Lucro Real')], max_length=30)),
                ('crt', models.CharField(blank=True, choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - excesso sublimite'), ('3', 'Regime Normal')], max_length=1)),
                ('cnae', models.CharField(blank=True, max_length=7)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('municipio', models.CharField(blank=True, max_length=200)),
                ('municipio_ibge', models.CharField(blank=True, max_length=7)),
                ('logradouro', models.CharField(blank=True, max_length=300)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=200)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('ambiente_fiscal', models.CharField(choices=[('HOMOLOGACAO', 'Homologação'), ('PRODUCAO', 'Produção')], default='HOMOLOGACAO', max_length=20)),
                ('provider_fiscal', models.CharField(choices=[('FAKE', 'Fake'), ('NFEIO', 'NFE.io'), ('FOCUS_NFE', 'Focus NFe'), ('PLUGNOTAS', 'PlugNotas')], default='FAKE', max_length=20)),
                ('provider_company_id', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_fiscal', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuração Fiscal da Empresa',
                'verbose_name_plural': 'Configurações Fiscais das Empresas',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['company', 'ativo'], name='fiscal_conf_company_7c2cd7_idx'), models.Index(fields=['company', 'ambiente_fiscal'], name='fiscal_conf_company_6578a7_idx'), models.Index(fields=['company', 'provider_fiscal'], name='fiscal_conf_company_b7e04c_idx')],
            },
        ),
    ]
