# Generated by Django 5.2 on 2026-05-18 12:44

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=300, verbose_name='Nome / Razão Social')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('cpf_cnpj', models.CharField(max_length=14, verbose_name='CPF / CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('rua', models.CharField(blank=True, max_length=300, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Limite de Crédito')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo Devedor')),
                ('bloqueado', models.BooleanField(default=False)),
                ('data_ultimo_pagamento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['company_id', 'bloqueado'], name='clientes_cl_company_b7e5dc_idx'), models.Index(fields=['company_id', 'saldo_devedor'], name='clientes_cl_company_ce8612_idx'), models.Index(fields=['company_id', 'nome'], name='clientes_cl_company_dedcb1_idx'), models.Index(fields=['cpf_cnpj'], name='clientes_cl_cpf_cnp_0eeb49_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company_id', 'cpf_cnpj'), name='unique_cpf_cnpj_per_company_active')],
            },
        ),
    ]
