# Generated by Django 5.2 on 2026-05-31 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_company_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_cl_company_b7e5dc_idx',
            old_name='clientes_cl_company_bloq_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_cl_company_ce8612_idx',
            old_name='clientes_cl_company_saldo_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_cl_company_dedcb1_idx',
            old_name='clientes_cl_company_nome_idx',
        ),
    ]
