# Generated by Django 5.2 on 2026-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_clientes_cl_company_bloq_idx_clientes_cl_company_b7e5dc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_pais',
            field=models.CharField(blank=True, default='1058', max_length=4),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contribuinte_icms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indicador_ie',
            field=models.CharField(choices=[('CONTRIBUINTE', 'Contribuinte ICMS'), ('ISENTO', 'Isento'), ('NAO_CONTRIBUINTE', 'Não contribuinte')], default='NAO_CONTRIBUINTE', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio_ibge',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, default='BRASIL', max_length=80),
        ),
    ]
