# Generated by Django 5.2 on 2026-05-31 21:03

import apps.notas_entrada.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletos', '0001_initial'),
        ('empresas', '0002_rename_empresas_em_cnpj_idx_empresas_em_cnpj_fe5b68_idx_and_more'),
        ('estoque', '0001_initial'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fornecedor_nome_xml', models.CharField(blank=True, max_length=300)),
                ('fornecedor_cnpj_xml', models.CharField(blank=True, max_length=14)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('chave_acesso', models.CharField(blank=True, max_length=44)),
                ('numero', models.CharField(max_length=15)),
                ('serie', models.CharField(max_length=3)),
                ('modelo', models.CharField(default='55', max_length=2)),
                ('data_emissao', models.DateField()),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('xml_file', models.FileField(blank=True, null=True, upload_to=apps.notas_entrada.models._nfe_xml_upload_path)),
                ('status', models.CharField(choices=[('AGUARDANDO_REVISAO', 'Aguardando Revisão'), ('CONFIRMADA', 'Confirmada'), ('REJEITADA', 'Rejeitada'), ('IMPORTADA', 'Importada'), ('PROCESSANDO', 'Processando'), ('ERRO', 'Erro')], default='AGUARDANDO_REVISAO', max_length=25)),
                ('payload_extraido', models.JSONField(blank=True, default=dict)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('rejeitado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('erro_codigo', models.CharField(blank=True, max_length=80)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=140)),
                ('boleto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nota_entrada', to='boletos.boletoocr')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrada', to='empresas.empresa')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_entrada_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('conta_pagar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nota_entrada', to='financeiro.contapagar')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_entrada_criadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrada', to='estoque.fornecedor')),
                ('rejeitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_entrada_rejeitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Entrada',
                'verbose_name_plural': 'Notas Fiscais de Entrada',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscalEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('descricao_original', models.CharField(max_length=500)),
                ('codigo_fornecedor', models.CharField(blank=True, max_length=80)),
                ('codigo_barras', models.CharField(blank=True, max_length=80)),
                ('ncm', models.CharField(blank=True, max_length=10)),
                ('cfop', models.CharField(blank=True, max_length=5)),
                ('unidade', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_total_item', models.DecimalField(decimal_places=2, max_digits=14)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_ipi_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_icms_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ignorado', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_nota_entrada', to='empresas.empresa')),
                ('movimentacao_estoque', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_nota_entrada', to='estoque.movimentacaoestoque')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_nota_entrada', to='estoque.produto')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='notas_entrada.notafiscalentrada')),
            ],
            options={
                'verbose_name': 'Item de Nota Fiscal de Entrada',
                'verbose_name_plural': 'Itens de Nota Fiscal de Entrada',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoNotaFiscalEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('evento', models.CharField(choices=[('XML_IMPORTADO', 'XML Importado'), ('FORNECEDOR_VINCULADO', 'Fornecedor Vinculado'), ('ITEM_PRODUTO_VINCULADO', 'Produto Vinculado ao Item'), ('ITEM_IGNORADO', 'Item Ignorado'), ('CONFIRMADA', 'Nota Confirmada'), ('ENTRADA_ESTOQUE_CRIADA', 'Entrada de Estoque Criada'), ('CONTA_PAGAR_CRIADA', 'Conta a Pagar Criada'), ('REJEITADA', 'Nota Rejeitada')], max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_nota_entrada', to='empresas.empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_nota_entrada', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='notas_entrada.notafiscalentrada')),
            ],
            options={
                'verbose_name': 'Histórico de Nota Fiscal de Entrada',
                'verbose_name_plural': 'Históricos de Notas Fiscais de Entrada',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['company', 'status', 'created_at'], name='notas_entra_company_a7e2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['company', 'fornecedor', 'data_emissao'], name='notas_entra_company_6d82b3_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['company', 'data_emissao'], name='notas_entra_company_f9a2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['company', 'chave_acesso'], name='notas_entra_company_064abc_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['company', 'sha256'], name='notas_entra_company_02e75e_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['company', 'criado_por', 'created_at'], name='notas_entra_company_963d16_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['company', 'conta_pagar'], name='notas_entra_company_ad1ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalentrada',
            index=models.Index(fields=['company', 'fornecedor_cnpj_xml'], name='notas_entra_company_e51ba7_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalentrada',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('chave_acesso', ''), _negated=True)), fields=('company', 'chave_acesso'), name='notas_entrada_unique_chave_acesso_company_active'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalentrada',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('sha256', ''), _negated=True)), fields=('company', 'sha256'), name='notas_entrada_unique_sha256_company_active'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalentrada',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='notas_entrada_unique_idempotency_company_active'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalentrada',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='notas_entrada_valor_total_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalentrada',
            constraint=models.CheckConstraint(condition=models.Q(('valor_produtos__gte', 0)), name='notas_entrada_valor_produtos_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='itemnotafiscalentrada',
            index=models.Index(fields=['company', 'nota', 'ordem'], name='notas_entra_company_e73b11_idx'),
        ),
        migrations.AddIndex(
            model_name='itemnotafiscalentrada',
            index=models.Index(fields=['company', 'produto'], name='notas_entra_company_c8d9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='itemnotafiscalentrada',
            index=models.Index(fields=['company', 'codigo_barras'], name='notas_entra_company_75ba18_idx'),
        ),
        migrations.AddIndex(
            model_name='itemnotafiscalentrada',
            index=models.Index(fields=['company', 'nota', 'ignorado'], name='notas_entra_company_0b5947_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemnotafiscalentrada',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='notas_entrada_item_quantidade_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='itemnotafiscalentrada',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='notas_entrada_item_valor_unitario_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='itemnotafiscalentrada',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total_item__gte', 0)), name='notas_entrada_item_valor_total_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='historiconotafiscalentrada',
            index=models.Index(fields=['company', 'nota', 'created_at'], name='notas_entra_company_28c2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='historiconotafiscalentrada',
            index=models.Index(fields=['company', 'evento', 'created_at'], name='notas_entra_company_7a84a6_idx'),
        ),
        migrations.AddIndex(
            model_name='historiconotafiscalentrada',
            index=models.Index(fields=['created_by', 'created_at'], name='notas_entra_created_4e51da_idx'),
        ),
    ]
