# Generated by Django 5.2 on 2026-05-31 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas_entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnotafiscalentrada',
            options={'ordering': ['ordem'], 'verbose_name': 'Item de Nota Fiscal de Entrada', 'verbose_name_plural': 'Itens de Nota Fiscal de Entrada'},
        ),
    ]
