# Generated by Django 5.2 on 2026-06-03 02:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itemvenda',
            new_name='vendas_item_company_0c3807_idx',
            old_name='vendas_iv_company_venda_idx',
        ),
        migrations.RenameIndex(
            model_name='itemvenda',
            new_name='vendas_item_company_bd9836_idx',
            old_name='vendas_iv_company_produto_idx',
        ),
        migrations.RenameIndex(
            model_name='venda',
            new_name='vendas_vend_company_02e495_idx',
            old_name='vendas_ve_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='venda',
            new_name='vendas_vend_company_b07480_idx',
            old_name='vendas_ve_company_numero_idx',
        ),
        migrations.RenameIndex(
            model_name='venda',
            new_name='vendas_vend_company_94cf65_idx',
            old_name='vendas_ve_company_cliente_idx',
        ),
        migrations.RenameIndex(
            model_name='venda',
            new_name='vendas_vend_company_9e40ee_idx',
            old_name='vendas_ve_company_created_idx',
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade_informada',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
