# Generated by Django 5.2 on 2026-06-03 16:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_vendas_iv_company_venda_idx_vendas_item_company_0c3807_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='custo_total_historico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='custo_unitario_historico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
